apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-tls-cert
  namespace: default
spec:
  secretName: myapp-tls
  duration: 2160h 
  issuerRef:
    name: selfsigned-issuer
  commonName: myapp.example.local 
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  
  #dnsNames:
  #- www.myapp.newtech.academy
